package com.ghadirb.yadavar.receivers

import android.app.Notification
import android.app.PendingIntent
import android.app.Service
import android.content.Context
import android.content.Intent
import android.content.pm.ServiceInfo
import android.media.AudioAttributes
import android.media.AudioFocusRequest
import android.media.AudioManager
import android.media.MediaPlayer
import android.os.Build
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.os.PowerManager
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import android.util.Log
import androidx.core.app.NotificationCompat
import com.ghadirb.yadavar.R
import com.ghadirb.yadavar.YadavarApplication
import com.ghadirb.yadavar.ui.reminders.FullScreenAlarmActivity
import com.ghadirb.yadavar.utils.AIBackendClient
import com.ghadirb.yadavar.utils.AIHelper
import com.ghadirb.yadavar.utils.ReminderSound
import com.ghadirb.yadavar.utils.SubscriptionManager
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.util.Locale

/**
 * Smart spoken alert: local ringtone immediately, then a natural Persian sentence
 * generated by the online model and spoken by online TTS, repeating until the user
 * taps Done / Snooze (with a 20-minute safety cap).
 */
class SmartReminderTtsService : Service() {

    private var tts: TextToSpeech? = null
    private val handler = Handler(Looper.getMainLooper())
    private var speakJob: Job? = null
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)
    private var currentReminderId: Long = -1
    private var currentTitle: String = ""
    private var cloudPlayer: MediaPlayer? = null
    private var localPlayer: MediaPlayer? = null
    private var audioFocusRequest: AudioFocusRequest? = null
    private var pendingSpeakText: String = ""
    private var startedAt: Long = 0L
    private var savedAlarmVolume: Int? = null

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        runningInstance = this
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        val reminderId = intent?.getLongExtra("reminder_id", -1) ?: -1
        val title = intent?.getStringExtra("reminder_title") ?: "یادآوری"
        val description = intent?.getStringExtra("reminder_description") ?: ""
        val soundUri = intent?.getStringExtra("sound_uri") ?: ReminderSound.DEFAULT_ALARM
        if (reminderId <= 0) {
            stopSelfCompletely()
            return START_NOT_STICKY
        }
        try {
            if (currentReminderId != -1L && currentReminderId != reminderId) stopSpeakingLoop()
            currentReminderId = reminderId
            currentTitle = title
            startedAt = System.currentTimeMillis()
            val notification = buildNotification(reminderId, title, getString(R.string.smart_tts_preparing))
            if (Build.VERSION.SDK_INT >= 34) {
                startForeground(
                    NOTIFICATION_ID_BASE + reminderId.toInt(),
                    notification,
                    ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE
                )
            } else {
                startForeground(NOTIFICATION_ID_BASE + reminderId.toInt(), notification)
            }
        } catch (e: Exception) {
            Log.e(TAG, "startForeground failed", e)
            stopSelfCompletely()
            return START_NOT_STICKY
        }

        ensureAudibleAlarmStream()
        requestAlarmAudioFocus()
        playLocalAlarm(soundUri)

        val template = spokenTemplate(title, description)
        pendingSpeakText = template
        notifySpokenText(reminderId, template)
        speakJob?.cancel()
        speakJob = scope.launch {
            val cloud = withContext(Dispatchers.IO) {
                runCatching {
                    withTimeoutOrNull(CLOUD_TIMEOUT_MS) {
                        prepareCloudSpeech(title, description, template)
                    }
                }.onFailure { Log.w(TAG, "cloud smart alert failed", it) }.getOrNull()
            }
            if (currentReminderId != reminderId) return@launch
            if (cloud != null) {
                pendingSpeakText = cloud.text
                notifySpokenText(reminderId, cloud.text)
                updateNotification(reminderId, title, cloud.text)
                stopLocalAlarm()
                playCloud(cloud.file.absolutePath)
            } else {
                Log.w(TAG, "cloud TTS unavailable: ${AIBackendClient.lastError}")
                updateNotification(reminderId, title, template)
                initDeviceTts(template)
            }
        }
        return START_REDELIVER_INTENT
    }

    private suspend fun prepareCloudSpeech(
        title: String,
        description: String,
        template: String
    ): AIBackendClient.SmartAlertAudio? {
        val combined = AIBackendClient.smartAlert(this, title, description)
        if (combined != null) return combined

        val hasPersonalKey = SubscriptionManager.hasPersonalKey(this)
        val spoken = rewriteSpoken(title, description, template, hasPersonalKey)
        pendingSpeakText = spoken
        val file = if (hasPersonalKey) {
            AIHelper.synthesizeSpeech(this, spoken)
        } else {
            AIBackendClient.synthesize(this, spoken)
        } ?: return null
        return AIBackendClient.SmartAlertAudio(spoken, file)
    }

    private suspend fun rewriteSpoken(
        title: String,
        description: String,
        template: String,
        hasPersonalKey: Boolean
    ): String {
        val rewritten = if (hasPersonalKey) {
            AIHelper.generateText(
                this,
                SPOKEN_SYSTEM_PROMPT,
                spokenUserPrompt(title, description),
                maxTokens = 80
            )
        } else {
            val messages = JSONArray()
                .put(JSONObject().put("role", "system").put("content", SPOKEN_SYSTEM_PROMPT))
                .put(JSONObject().put("role", "user").put("content", spokenUserPrompt(title, description)))
            AIBackendClient.chat(this, messages, maxTokens = 80, temperature = 0.6)
        }
        val cleaned = rewritten?.trim()?.trim('"', '«', '»', '\'')?.take(220).orEmpty()
        return cleaned.ifBlank { template }
    }

    private fun alarmAttrs(): AudioAttributes =
        AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_ALARM)
            .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
            .build()

    private fun ensureAudibleAlarmStream() {
        try {
            val am = getSystemService(AUDIO_SERVICE) as AudioManager
            val max = am.getStreamMaxVolume(AudioManager.STREAM_ALARM)
            val cur = am.getStreamVolume(AudioManager.STREAM_ALARM)
            if (max > 0 && cur < (max / 3).coerceAtLeast(1)) {
                savedAlarmVolume = cur
                am.setStreamVolume(AudioManager.STREAM_ALARM, (max * 3 / 4).coerceAtLeast(1), 0)
            }
        } catch (_: Exception) {
        }
    }

    private fun restoreAlarmVolume() {
        val saved = savedAlarmVolume ?: return
        savedAlarmVolume = null
        try {
            val am = getSystemService(AUDIO_SERVICE) as AudioManager
            am.setStreamVolume(AudioManager.STREAM_ALARM, saved, 0)
        } catch (_: Exception) {
        }
    }

    private fun playLocalAlarm(soundValue: String) {
        val uri = ReminderSound.toUri(this, soundValue) ?: return
        try {
            localPlayer?.release()
            localPlayer = MediaPlayer().apply {
                setAudioAttributes(alarmAttrs())
                setDataSource(this@SmartReminderTtsService, uri)
                isLooping = true
                setWakeMode(this@SmartReminderTtsService, PowerManager.PARTIAL_WAKE_LOCK)
                setVolume(1f, 1f)
                prepare()
                start()
            }
        } catch (e: Exception) {
            Log.e(TAG, "local alarm failed", e)
        }
    }

    private fun stopLocalAlarm() {
        runCatching {
            localPlayer?.apply { if (isPlaying) stop(); release() }
        }
        localPlayer = null
    }

    private fun stillActive(): Boolean {
        if (currentReminderId == -1L) return false
        if (System.currentTimeMillis() - startedAt >= MAX_DURATION_MS) {
            stopSelfCompletely()
            return false
        }
        return true
    }

    private fun playCloud(path: String) {
        if (!stillActive()) return
        if (!File(path).exists()) {
            initDeviceTts(pendingSpeakText)
            return
        }
        try {
            cloudPlayer?.release()
            cloudPlayer = MediaPlayer().apply {
                setAudioAttributes(alarmAttrs())
                setDataSource(path)
                isLooping = false
                setWakeMode(this@SmartReminderTtsService, PowerManager.PARTIAL_WAKE_LOCK)
                setVolume(1f, 1f)
                setOnCompletionListener {
                    handler.postDelayed({
                        if (stillActive()) playCloud(path)
                    }, REPEAT_GAP_MS)
                }
                setOnErrorListener { _, what, extra ->
                    Log.e(TAG, "cloud player error what=$what extra=$extra")
                    initDeviceTts(pendingSpeakText)
                    true
                }
                prepare()
                start()
            }
        } catch (e: Exception) {
            Log.e(TAG, "cloud play failed", e)
            initDeviceTts(pendingSpeakText)
        }
    }

    private fun initDeviceTts(text: String) {
        if (tts != null) {
            speakOnce(text)
            return
        }
        tts = TextToSpeech(this) { status ->
            if (currentReminderId == -1L) return@TextToSpeech
            if (status != TextToSpeech.SUCCESS) {
                Log.w(TAG, "device TTS init failed, keeping local alarm")
                return@TextToSpeech
            }
            pickTtsLanguage()
            stopLocalAlarm()
            tts?.setSpeechRate(0.95f)
            tts?.setAudioAttributes(alarmAttrs())
            tts?.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                override fun onStart(utteranceId: String?) {}
                override fun onError(utteranceId: String?) {
                    handler.postDelayed({ if (stillActive()) speakOnce(pendingSpeakText) }, REPEAT_GAP_MS)
                }
                override fun onDone(utteranceId: String?) {
                    handler.postDelayed({ if (stillActive()) speakOnce(pendingSpeakText) }, REPEAT_GAP_MS)
                }
            })
            speakOnce(text)
        }
    }

    private fun pickTtsLanguage() {
        val faIr = tts?.setLanguage(Locale("fa", "IR")) ?: TextToSpeech.LANG_NOT_SUPPORTED
        val langOk = faIr != TextToSpeech.LANG_MISSING_DATA && faIr != TextToSpeech.LANG_NOT_SUPPORTED
        if (langOk) return
        val fa = tts?.setLanguage(Locale("fa")) ?: TextToSpeech.LANG_NOT_SUPPORTED
        if (fa != TextToSpeech.LANG_MISSING_DATA && fa != TextToSpeech.LANG_NOT_SUPPORTED) return
        tts?.language = Locale.getDefault()
    }

    private fun speakOnce(text: String) {
        if (!stillActive()) return
        tts?.speak(text, TextToSpeech.QUEUE_FLUSH, null, "smart_$currentReminderId")
    }

    private fun requestAlarmAudioFocus() {
        try {
            val am = getSystemService(AUDIO_SERVICE) as AudioManager
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                val req = AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT)
                    .setAudioAttributes(alarmAttrs())
                    .build()
                audioFocusRequest = req
                am.requestAudioFocus(req)
            } else {
                @Suppress("DEPRECATION")
                am.requestAudioFocus(null, AudioManager.STREAM_ALARM, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT)
            }
        } catch (_: Exception) {
        }
    }

    private fun fullScreenIntent(reminderId: Long, title: String): Intent =
        Intent(this, FullScreenAlarmActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP
            putExtra("reminder_id", reminderId)
            putExtra("reminder_title", title)
            putExtra("alert_type", "SMART")
            putExtra("spoken_text", pendingSpeakText)
        }

    private fun buildNotification(reminderId: Long, title: String, body: String): Notification {
        val fullPi = PendingIntent.getActivity(
            this, reminderId.toInt(), fullScreenIntent(reminderId, title),
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
        )
        val donePi = PendingIntent.getBroadcast(
            this, ("done$reminderId").hashCode(),
            Intent(this, ReminderActionReceiver::class.java).apply {
                action = ReminderActionReceiver.ACTION_DONE
                putExtra("reminder_id", reminderId)
            },
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
        )
        return NotificationCompat.Builder(this, YadavarApplication.SMART_TTS_CHANNEL_ID)
            .setSmallIcon(R.drawable.ic_notification_reminder)
            .setContentTitle(title)
            .setContentText(body)
            .setStyle(NotificationCompat.BigTextStyle().bigText(body))
            .setOngoing(true)
            .setSilent(true)
            .setCategory(NotificationCompat.CATEGORY_ALARM)
            .setContentIntent(fullPi)
            .addAction(R.drawable.ic_check, getString(R.string.action_done), donePi)
            .setForegroundServiceBehavior(NotificationCompat.FOREGROUND_SERVICE_IMMEDIATE)
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .build()
    }

    private fun updateNotification(reminderId: Long, title: String, body: String) {
        try {
            val nm = getSystemService(NOTIFICATION_SERVICE) as android.app.NotificationManager
            nm.notify(NOTIFICATION_ID_BASE + reminderId.toInt(), buildNotification(reminderId, title, body))
        } catch (_: Exception) {
        }
    }

    private fun stopSpeakingLoop() {
        handler.removeCallbacksAndMessages(null)
        speakJob?.cancel()
        runCatching { tts?.stop(); tts?.shutdown() }
        tts = null
        runCatching { cloudPlayer?.stop(); cloudPlayer?.release() }
        cloudPlayer = null
        stopLocalAlarm()
        try {
            val am = getSystemService(AUDIO_SERVICE) as AudioManager
            audioFocusRequest?.let {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) am.abandonAudioFocusRequest(it)
            }
        } catch (_: Exception) {
        }
        audioFocusRequest = null
        restoreAlarmVolume()
    }

    private fun stopSelfCompletely() {
        stopSpeakingLoop()
        currentReminderId = -1
        runCatching { stopForeground(STOP_FOREGROUND_REMOVE) }
        stopSelf()
    }

    override fun onDestroy() {
        stopSpeakingLoop()
        scope.cancel()
        if (runningInstance === this) runningInstance = null
        super.onDestroy()
    }

    companion object {
        private const val TAG = "SmartReminderTts"
        private const val NOTIFICATION_ID_BASE = 90000
        private const val REPEAT_GAP_MS = 1600L
        private const val MAX_DURATION_MS = 20 * 60 * 1000L
        private const val CLOUD_TIMEOUT_MS = 45_000L
        private const val SPOKEN_SYSTEM_PROMPT =
            "تو گوینده هشدار یادآور هستی. فقط یک جمله کوتاه محاوره‌ای فارسی برگردان که با صدای بلند برای کاربر خوانده شود. بدون اموجی، بدون نقل‌قول، بدون توضیح اضافه."

        @Volatile
        private var runningInstance: SmartReminderTtsService? = null

        @Volatile
        var spokenTextListener: ((Long, String) -> Unit)? = null

        fun spokenTemplate(title: String, description: String): String {
            val t = title.trim().ifBlank { "یک کار" }
            val d = description.trim()
            return if (d.isBlank()) "سلام، الان وقتشه که $t. لطفاً انجامش بده."
            else "سلام، الان وقتشه که $t. $d"
        }

        private fun spokenUserPrompt(title: String, description: String): String {
            val d = description.trim()
            return if (d.isBlank()) "عنوان یادآوری: $title"
            else "عنوان یادآوری: $title\nتوضیح: $d"
        }

        private fun notifySpokenText(reminderId: Long, text: String) {
            spokenTextListener?.invoke(reminderId, text)
        }

        fun currentSpokenText(reminderId: Long): String {
            val instance = runningInstance ?: return ""
            return if (instance.currentReminderId == reminderId) instance.pendingSpeakText else ""
        }

        fun start(context: Context, reminderId: Long, title: String, description: String, soundUri: String = ReminderSound.DEFAULT_ALARM) {
            val intent = Intent(context, SmartReminderTtsService::class.java).apply {
                putExtra("reminder_id", reminderId)
                putExtra("reminder_title", title)
                putExtra("reminder_description", description)
                putExtra("sound_uri", soundUri)
            }
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) context.startForegroundService(intent)
            else context.startService(intent)
        }

        fun stop(reminderId: Long = -1) {
            val instance = runningInstance ?: return
            if (reminderId == -1L || instance.currentReminderId == reminderId) instance.stopSelfCompletely()
        }
    }
}
